@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzUzODgwMDF9.Qx8bMNkKzf-th6QFPIxFAy78kgeDYOLGPqOgaM9J_p0

###CREATE NEW PRODUCT
POST http://localhost:3000/products.json 
Content-Type: application/json 

{

"name": "Candy Corn",
"price": 1,
"image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Candy-Corn.jpg/1200px-Candy-Corn.jpg",
"description": "Wax covered sweet corn candy",
"supplier_id": 1

}

###INDEX - SHOW ALL PRODUCTS
GET http://localhost:3000/products.json
Authorization: Bearer {{jwt}}

###SHOW - SHOW A SINGLE PRODUCT
GET http://localhost:3000/products/11.json 
Authorization: Bearer {{jwt}}

###UPDATE - UPDATE A SINGLE PRODUCT
PATCH http://localhost:3000/products/11.json 
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Pikachu",
  "price": 1000,
  "image_url": "https://secure.img1-fg.wfcdn.com/im/77981853/resize-h755-w755%5Ecompr-r85/8470/84707680/Pokemon+Pikachu+Wall+Decal.jpg",
  "description": "Don't get too close before you tame him!"

}

###DELETE - DELETE A SINGLE PRODUCT
DELETE http://localhost:3000/products/10.json
Authorization: Bearer {{jwt}}


### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "mike",
  "email": "mike@mike.com",
  "password": "password",
  "password_confirmation": "password"
}



### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "mike@mike.com",
  "password": "password"
}



###### STILL NEED TO UPDATE SO YOU CANNOT DO STUFF UNLESS LOGGED IN, REVEIEVES ERROR. 23:00 min in videp

#### Still need to allow a user to add images whenthey create a product. 



### ORDERS CREATE
POST http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json 

{
  "product_id": "1",
  "quantity": "3"
}


### ORDERS INDEX
GET http://localhost:3000/orders.json


